name: activityBiosca_Sergi
on:
  push:
    branches:
      - nodejs_environment_job
jobs:
  linter-execution:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10, 12]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: github/super-linter@v4
      - uses: adeloyedeji/github-actions-hello@v1.0 
        with:
          who-to-greet: '2DAW BIOSKIN'
        env:
          DEFAULT_BRANCH: nodejs_environment_job
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true
  test-execution:
    runs-on: ubuntu-latest
    needs: linter-execution
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run jest tests
        run: npm install jest && npm test