name: activityBiosca_Sergis
on:
  push:
    branches:
      - nodejs_jest_job
jobs:
  linter-execution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: github/super-linter@v4
    env:
      DEFAULT_BRANCH: nodejs_jest_job
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      LINTER_RULES_PATH: /
      JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
      VALIDATE_JAVASCRIPT_ES: true        
  test-execution:
    runs-on: ubuntu-latest
    needs: linter-execution
    steps:
      - uses: actions/checkout@v2 
      - run: npm install -D 
      - run: npm run test
        id: jest 
        continue-on-error: true 
      - name: Check on failures 
        if: steps.jest.outcome  != 'success' 
        run: echo "Bioskin hay error"        